//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacMan.Mapy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class bludiste_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal bludiste_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacMan.Mapy.bludiste_1", typeof(bludiste_1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string BlinkyRozptyl_radekIdx {
            get {
                return ResourceManager.GetString("BlinkyRozptyl.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string BlinkyRozptyl_sloupecIdx {
            get {
                return ResourceManager.GetString("BlinkyRozptyl.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string BlinkyStart_radekIdx {
            get {
                return ResourceManager.GetString("BlinkyStart.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string BlinkyStart_sloupecIdx {
            get {
                return ResourceManager.GetString("BlinkyStart.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string ClydeRozptyl_radekIdx {
            get {
                return ResourceManager.GetString("ClydeRozptyl.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ClydeRozptyl_sloupecIdx {
            get {
                return ResourceManager.GetString("ClydeRozptyl.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string ClydeStart_radekIdx {
            get {
                return ResourceManager.GetString("ClydeStart.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ClydeStart_sloupecIdx {
            get {
                return ResourceManager.GetString("ClydeStart.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string InkyRozptyl_radekIdx {
            get {
                return ResourceManager.GetString("InkyRozptyl.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string InkyRozptyl_sloupecIdx {
            get {
                return ResourceManager.GetString("InkyRozptyl.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string InkyStart_radekIdx {
            get {
                return ResourceManager.GetString("InkyStart.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string InkyStart_sloupecIdx {
            get {
                return ResourceManager.GetString("InkyStart.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string PacManStart_radekIdx {
            get {
                return ResourceManager.GetString("PacManStart.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string PacManStart_sloupecIdx {
            get {
                return ResourceManager.GetString("PacManStart.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PinkyRozptyl_radekIdx {
            get {
                return ResourceManager.GetString("PinkyRozptyl.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PinkyRozptyl_sloupecIdx {
            get {
                return ResourceManager.GetString("PinkyRozptyl.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string PinkyStart_radekIdx {
            get {
                return ResourceManager.GetString("PinkyStart.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string PinkyStart_sloupecIdx {
            get {
                return ResourceManager.GetString("PinkyStart.sloupecIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Vychod_radekIdx {
            get {
                return ResourceManager.GetString("Vychod.radekIdx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Vychod_sloupecIdx {
            get {
                return ResourceManager.GetString("Vychod.sloupecIdx", resourceCulture);
            }
        }
    }
}
